services:
    # php app
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/local/nginx/:/etc/nginx/conf.d/
        ports:
            - "8989:80"
        networks:
            - laravel

    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "9000:80"
        networks:
            - laravel

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/local/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel

    # mailhog
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
