services:
    php:
        build:
            context: .
            dockerfile: ./.docker/dev/Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./:/var/www/html
            - ./storage:/var/www/html/storage
        networks:
            - net
        depends_on:
            - mysql
            - mailhog
            - redis
            - minio
    nginx:
        image: nginx:alpine
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
            - ./.docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - net
    mysql:
        image: mysql:latest
        environment:
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - net
    dbeaver:
        image: dbeaver/cloudbeaver
        environment:
            - CB_SERVER_PORT=8978
            - CB_SERVER_NAME=CloudBeaver
            - CB_ADMIN_NAME=${DB_USERNAME}
            - CB_ADMIN_PASSWORD=${DB_PASSWORD}
            - CB_APP_LOGS=info
            - CB_WORKSPACE_DIR=/opt/cloudbeaver/workspace
        volumes:
            - dbeaver:/opt/cloudbeaver/workspace
        ports:
            - 8978:8978
        depends_on:
            - mysql
        networks:
            - net
    redisinsight:
        image: redis/redisinsight:latest
        container_name: redisinsight
        ports:
            - "8001:8001"
            - "5540:5540"
        depends_on:
            - redis
        networks:
            - net
    mailhog:
        image: mailhog/mailhog
        ports:
            - 1026:1025
            - 8025:8025
        networks:
            - net
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - net
    minio:
        image: minio/minio:latest
        environment:
            MINIO_ROOT_USER: ${DB_USERNAME}
            MINIO_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 9001:9001
        command: minio server /data/minio --console-address ":9001"
        volumes:
            - minio:/data/minio
        networks:
            - net
volumes:
    minio:
    dbdata:
    dbeaver:
networks:
    net:
        driver: bridge